# Generated by Django 2.2.1 on 2019-07-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funccrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('normal', '일반'), ('notice', '공지'), ('task', '과제')], default='normal', max_length=20),
        ),
    ]
